services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    intaro_pinba.script_name_configure.listener:
        class: Intaro\PinbaBundle\EventListener\ScriptNameConfigureListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }

    intaro_pinba.stopwatch:
        class: Intaro\PinbaBundle\Stopwatch\Stopwatch

    Intaro\PinbaBundle\Stopwatch\Stopwatch: '@intaro_pinba.stopwatch'
    Intaro\PinbaBundle\EventListener\ScriptNameConfigureListener: '@intaro_pinba.script_name_configure.listener'

    templating.engine.twig:
        class: Intaro\PinbaBundle\Twig\TimedTwigEngine
        public: false
        arguments:
            - "@twig"
            - "@templating.name_parser"
            - "@templating.locator"
            - "@intaro_pinba.stopwatch"

    doctrine.dbal.logger:
        class: Intaro\PinbaBundle\Logger\DbalLogger
        public: false
        arguments:
            - "@intaro_pinba.stopwatch"
            - "%intaro_pinba.doctrine.database_host%"
