services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    intaro_pinba.stopwatch:
        class: Intaro\PinbaBundle\Stopwatch\Stopwatch

    Intaro\PinbaBundle\Stopwatch\Stopwatch: '@intaro_pinba.stopwatch'

    Intaro\PinbaBundle\EventListener\ScriptNameConfigureListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }

    twig:
        class: Intaro\PinbaBundle\Twig\EnvironmentDecorating
        public: true
        configurator: ['@twig.configurator.environment', 'configure']
        arguments:
            $loader: '@twig.loader'
            $stopwatch: '@intaro_pinba.stopwatch'
        calls:
            - [ addRuntimeLoader, ["@twig.runtime_loader"] ]
            - [ addGlobal, ["app", "@twig.app_variable"] ]

    Twig\Environment: '@twig'

    doctrine.dbal.logger:
        class: Intaro\PinbaBundle\Logger\DbalLogger
        public: false
        arguments:
            - "@intaro_pinba.stopwatch"
            - "%intaro_pinba.doctrine.database_host%"
