name: CI

on:
  pull_request:
  push:
    branches:
      - "*.*"
      - master

jobs:
  static-analysis:
    runs-on: ubuntu-20.04
    name: "Static analysis"
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-version }}
          coverage: "none"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2

      - name: "Run code-style check"
        run: composer phpcs
